import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Suspense } from "react";
// import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Portfolio Medium",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={inter.className}
            // data-aos-easing="ease"
            // data-aos-duration="400"
            // data-aos-delay="0"
            >
                {/* <Suspense fallback={<Loading />} /> */}
                {children}</body>
        </html>
    );
}
